apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  namespace: dev-v2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30050
  selector:
    app: frontend
  type: NodePort
