apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udacityshop-dev
spec:
  project: default
  source:
    repoURL: 'https://github.com/YungChunLu/github-action'
    path: kubernetes-manifests/dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
