apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udacityshop-dev-v2
spec:
  project: default
  source:
    repoURL: 'https://github.com/YungChunLu/github-action'
    path: kubernetes-manifests/dev-v2
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-v2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
