name: Uda'CityShop [latest tag] - Package with Docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build adservice
        uses: docker/build-push-action@v2
        with:
          context: ./src/adservice
          push: true
          tags: adservice:latest
