name: Uda'CityShop [sha tag] - Package with Docker

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          # images: |
          #   ${{ secrets.DOCKER_HUB_USERNAME }}/adservice
          #   ${{ secrets.DOCKER_HUB_USERNAME }}/frontend
          #   ${{ secrets.DOCKER_HUB_USERNAME }}/productcatalogservice
          #   ${{ secrets.DOCKER_HUB_USERNAME }}/currencyservice
          tags: |
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build adservice
        uses: docker/build-push-action@v2
        with:
          context: ./src/adservice
          file: ./src/adservice/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build frontend
        uses: docker/build-push-action@v2
        with:
          context: ./src/frontend
          file: ./src/frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      
      - name: Build productcatalogservice
        uses: docker/build-push-action@v2
        with:
          context: ./src/productcatalogservice
          file: ./src/productcatalogservice/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build currencyservice
        uses: docker/build-push-action@v2
        with:
          context: ./src/currencyservice
          file: ./src/currencyservice/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
